---
# Ensure the grafana config file exists.
- name: Ensure grafana config file exists
  file:
    path: "{{ config_location }}/agent-config.yaml"
    state: file

# Insert the process exporter config block from defaults/main.yml file
- name: Insert process exporter configuration block from defaults part 1
  notify:
    - Restart grafana
  blockinfile:
    path: "{{ config_location }}/agent-config.yaml"
    block: |
        {{ process_exporter_config_part1 | to_nice_yaml(indent=2) | indent(2, True) }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PROCESS EXPORTER PART 1"

# Loop over the host config found in the defaul/main.yml file.
- name: Write each config section for the processes hosted on the server {{ vars['proc_'+inventory_hostname] }}
  include_tasks: "write_process_config.yml"
  loop: "{{ vars['proc_'+inventory_hostname] }}"

# Insert the process exporter config block from defaults/main.yml file
- name: Insert process exporter configuration block from defaults part 2
  notify:
    - Restart grafana
  blockinfile:
    path: "{{ config_location }}/agent-config.yaml"
    block: |
        {{ process_exporter_config_part2 | to_nice_yaml(indent=4) | indent(4, True) }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PROCESS EXPORTER PART 2"

# Insert log config block from defaults/main.yml file
#- name: Insert log configuration block
#  notify:
#    - Restart grafana
#  blockinfile:
#    path: "{{ config_location }}/agent-config.yaml"
#    block: |
#        {{ log_config | to_nice_yaml(indent=2) | indent(0, True)}}
#    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR LOG EXPORTER"

# Loop over the host config found in the defaul/main.yml file.
#- name: Write each config section for the applications hosted on the server
#  include_tasks: "write_config.yml"
#  loop: "{{ vars[inventory_hostname] }}"