# Insert the promtail configuration which is defined in the default/main.yml file
- name: Insert configuration block
  notify:
    - Restart grafana
    - Remove null scrape_config
  blockinfile:
    path: "{{ config_location }}/agent-config.yaml"
    block: |
        {{ vars['app_'+item] | to_nice_yaml(indent=2) | indent(4, True) }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
